language: python

sudo: true
fast_finish: true

matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install Cython pytest pytest-cov coveralls
  - pip install -r requirements.txt
  - pip install .

script:
  - pytest --cov=yfinance/

after_success:
  - coveralls

branches:
  only:
    - master

notifications:
  slack: tradologics:HcnS6XusfcuS02waQPCG18oc
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
