{% set name = "yfinance" %}
{% set version = "0.1.45" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "516edfd062f400511f23a13254f6c0e6244e68d802a6fa9ad8ac131b0a7fcffe"

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - multitasking >=0.0.7
    - numpy >=1.15
    - pandas >=0.24
    - pip
    - python
    - requests >=2.20
  run:
    - multitasking >=0.0.7
    - numpy >=1.15
    - pandas >=0.24
    - python
    - requests >=2.20

test:
  imports:
    - yfinance

about:
  home: "https://github.com/ranaroussi/yfinance"
  license: "Apache Software"
  license_family: "APACHE"
  license_file: ""
  summary: "Yahoo! Finance market data downloader"
  description:
  doc_url: "https://github.com/ranaroussi/yfinance"
  dev_url: "https://pypi.python.org/pypi/yfinance"
  doc_source_url: https://github.com/ranaroussi/yfinance/blob/master/README.rst


extra:
  recipe-maintainers:
    - ranaroussi
